App\NoticeBoardBundle\Entity\NoticeBoards:
    type: entity
    table: null
#    repositoryClass: App\NoticeBoardBundle\Repository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        title:
            type: string
            length: 255
    lifecycleCallbacks: {  }
