home:
    path:     /
    controller: App\NoticeBoardBundle\Controller\DefaultController::index

listBoards:
    path:     /listCategories/
    controller: App\NoticeBoardBundle\Controller\DefaultController::listBoards

listBoardsNotices:
    path:     /listCategoriesAndRecipes/
    controller: App\NoticeBoardBundle\Controller\DefaultController::listBoardsNotices

showBoard:
    path:     /showCategory/{slug}
    controller: App\NoticeBoardBundle\Controller\DefaultController::showBoard

showNotice:
    path:     /showRecipe/{slug}
    controller: App\NoticeBoardBundle\Controller\DefaultController::showNotice

showNoticeSidebySideSingle:
    path:     /showSidebySide/{slug1}
    controller: App\NoticeBoardBundle\Controller\DefaultController::showSidebySideSingle
    
showNoticeSidebySide:
    path:     /showSidebySide/{slug1}/{slug2}
    controller: App\NoticeBoardBundle\Controller\DefaultController::showSidebySide
    
editNotice:
    path:     /editRecipe/{slug}
    controller: App\NoticeBoardBundle\Controller\DefaultController::editNotice

addNotice:
    path:     /addRecipe/
    controller: App\NoticeBoardBundle\Controller\DefaultController::addNotice

showAbout:
    path:     /about/
    controller: App\NoticeBoardBundle\Controller\DefaultController::showAbout

search:
    path:     /search
    controller: App\NoticeBoardBundle\Controller\DefaultController::search

viewGrid:
    path:   /grid/{slug}
    controller: App\NoticeBoardBundle\Controller\DefaultController::showNoticeGrid

categoriesnav:
    path: /categoriesnav
    controller: App\NoticeBoardBundle\Controller\DefaultController::categoriesNav

create_db:
    path:     /createdb
    controller: App\NoticeBoardBundle\Controller\DefaultController::create

# Build the API
apiGetCategories:
    path:   /api/categories
    controller: App\NoticeBoardBundle\Controller\DefaultController::apiGetCategories
    methods:    GET

apiCreateCategories:
    path:   /api/categories
    controller: App\NoticeBoardBundle\Controller\DefaultController::apiCreateCategories
    methods:    POST
