<?php

namespace NoticeBoardBundle\Repository;

/**
 * BloodFoodsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BloodFoodsRepository extends \Doctrine\ORM\EntityRepository
{
}
