<?php

namespace App\NoticeBoardBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * NoticeBoardNoticesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NoticeBoardNoticesRepository extends EntityRepository
{
}
