<?php

namespace NoticeBoardBundle\Repository;

/**
 * NoticeBoardsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NoticeBoardsRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllOrderedByName()
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT p.title FROM NoticeBoardBundle:NoticeBoards p'
            )
            ->getResult();
    }

    public function getArrayofBoards()
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT p.title FROM NoticeBoardBundle:NoticeBoards p'
            )
            ->getResult();
    }
}
