<?php

namespace App\NoticeBoardBundle\Repository;

/**
 * NoticeBoardNoticesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NoticeBoardNoticesRepository extends \Doctrine\ORM\EntityRepository
{
}
